apiVersion: apps/v1
kind: Deployment   #service demandé (deux possibilité : Deployement, Service, ConfigMap, Secret)
metadata:
  name: posts  #nom du kind (actuelement nom du Deployement)
  labels:
    app: posts #label du Deployment
spec:
  replicas: 1 # nombre de replique du template
  selector: # QUI :
    matchLabels:
      app: posts # appel du label du template utilisé (utilisé pour appeler ce kind (Deployment actuellement))
  template: # QUOI :
    metadata:
      labels:                       # QUOI/label 
        app: posts             # label utilisé pour appelier le template deployé
    spec:                           # QUOI / contenu
      containers:
      - name: posts             # nom du contenair
        image: posts           # image utilisé (récupérer dans )
        imagePullPolicy : Never
        ports:
        - containerPort: 80         # port des pods utilisés


---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 80